# Generated by Django 3.1.2 on 2020-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_auto_20201104_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='porfolio/images/'),
        ),
    ]
